# Generated by Django 4.2.23 on 2025-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='slack_channel_id',
            field=models.CharField(blank=True, help_text='Slack channel ID where the approval message was sent', max_length=50),
        ),
    ]
