# Generated by Django 4.2.23 on 2025-08-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0002_leaverequest_slack_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
