# Generated by Django 4.2.23 on 2025-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0003_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_leave_allowance',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of leave days allowed per month'),
        ),
    ]
