# Generated by Django 4.2.23 on 2025-08-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0005_team_employee_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-start_date'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leaverequestaudit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Leave Request Audit', 'verbose_name_plural': 'Leave Request Audits'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='leaverequestaudit',
            name='notes',
        ),
        migrations.AddField(
            model_name='leaverequestaudit',
            name='details',
            field=models.TextField(blank=True, help_text='System-generated or user-provided notes for this audit entry.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Optional notes from the manager regarding the decision.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(help_text='The last day of leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(help_text='The category of leave being requested.', on_delete=django.db.models.deletion.PROTECT, to='slackapp.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='A brief reason for the leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='slack_channel_id',
            field=models.CharField(blank=True, help_text='The channel ID where the approval message was sent.', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='slack_message_ts',
            field=models.CharField(blank=True, help_text='The timestamp ID of the Slack approval message.', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(help_text='The first day of leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequestaudit',
            name='action',
            field=models.CharField(help_text="Action performed (e.g., 'created', 'approved', 'rejected')", max_length=50),
        ),
    ]
